spring:
  cloud:
    config:
      server:
        git:
          password:
          username:
          clone-on-start: true
          uri: https://github.com/hafsafarah/configoptician.git
  application:
    name: config-service
server:
  port: 7761
